// Generated by gencpp from file gb_visual_detection_3d_msgs/goal_msg.msg
// DO NOT EDIT!


#ifndef GB_VISUAL_DETECTION_3D_MSGS_MESSAGE_GOAL_MSG_H
#define GB_VISUAL_DETECTION_3D_MSGS_MESSAGE_GOAL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gb_visual_detection_3d_msgs
{
template <class ContainerAllocator>
struct goal_msg_
{
  typedef goal_msg_<ContainerAllocator> Type;

  goal_msg_()
    : Class()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
    }
  goal_msg_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _normal_x_type;
  _normal_x_type normal_x;

   typedef double _normal_y_type;
  _normal_y_type normal_y;

   typedef double _normal_z_type;
  _normal_z_type normal_z;





  typedef boost::shared_ptr< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> const> ConstPtr;

}; // struct goal_msg_

typedef ::gb_visual_detection_3d_msgs::goal_msg_<std::allocator<void> > goal_msg;

typedef boost::shared_ptr< ::gb_visual_detection_3d_msgs::goal_msg > goal_msgPtr;
typedef boost::shared_ptr< ::gb_visual_detection_3d_msgs::goal_msg const> goal_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator1> & lhs, const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.normal_x == rhs.normal_x &&
    lhs.normal_y == rhs.normal_y &&
    lhs.normal_z == rhs.normal_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator1> & lhs, const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gb_visual_detection_3d_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a14534629947e0e1a95981852d661e1b";
  }

  static const char* value(const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa14534629947e0e1ULL;
  static const uint64_t static_value2 = 0xa95981852d661e1bULL;
};

template<class ContainerAllocator>
struct DataType< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gb_visual_detection_3d_msgs/goal_msg";
  }

  static const char* value(const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 normal_x\n"
"float64 normal_y\n"
"float64 normal_z\n"
;
  }

  static const char* value(const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.normal_x);
      stream.next(m.normal_y);
      stream.next(m.normal_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goal_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gb_visual_detection_3d_msgs::goal_msg_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "normal_x: ";
    Printer<double>::stream(s, indent + "  ", v.normal_x);
    s << indent << "normal_y: ";
    Printer<double>::stream(s, indent + "  ", v.normal_y);
    s << indent << "normal_z: ";
    Printer<double>::stream(s, indent + "  ", v.normal_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GB_VISUAL_DETECTION_3D_MSGS_MESSAGE_GOAL_MSG_H
