subscribers:

  camera_reading:
    topic: /cam2/color/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects_cam2

publishers:

  object_detector:
    topic: /darknet_ros/found_object_cam2
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes_cam2
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image_cam2
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: true
