// Generated by gencpp from file goal_getter/GoalPose.msg
// DO NOT EDIT!


#ifndef GOAL_GETTER_MESSAGE_GOALPOSE_H
#define GOAL_GETTER_MESSAGE_GOALPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace goal_getter
{
template <class ContainerAllocator>
struct GoalPose_
{
  typedef GoalPose_<ContainerAllocator> Type;

  GoalPose_()
    : goal_point()
    , goal_normal()  {
    }
  GoalPose_(const ContainerAllocator& _alloc)
    : goal_point(_alloc)
    , goal_normal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _goal_point_type;
  _goal_point_type goal_point;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_normal_type;
  _goal_normal_type goal_normal;





  typedef boost::shared_ptr< ::goal_getter::GoalPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::goal_getter::GoalPose_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPose_

typedef ::goal_getter::GoalPose_<std::allocator<void> > GoalPose;

typedef boost::shared_ptr< ::goal_getter::GoalPose > GoalPosePtr;
typedef boost::shared_ptr< ::goal_getter::GoalPose const> GoalPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::goal_getter::GoalPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::goal_getter::GoalPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::goal_getter::GoalPose_<ContainerAllocator1> & lhs, const ::goal_getter::GoalPose_<ContainerAllocator2> & rhs)
{
  return lhs.goal_point == rhs.goal_point &&
    lhs.goal_normal == rhs.goal_normal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::goal_getter::GoalPose_<ContainerAllocator1> & lhs, const ::goal_getter::GoalPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace goal_getter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::goal_getter::GoalPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_getter::GoalPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_getter::GoalPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_getter::GoalPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_getter::GoalPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_getter::GoalPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::goal_getter::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaffae3e07b3d469bde28c34c52087ab";
  }

  static const char* value(const ::goal_getter::GoalPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaffae3e07b3d469ULL;
  static const uint64_t static_value2 = 0xbde28c34c52087abULL;
};

template<class ContainerAllocator>
struct DataType< ::goal_getter::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "goal_getter/GoalPose";
  }

  static const char* value(const ::goal_getter::GoalPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::goal_getter::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped goal_point\n"
"geometry_msgs/PoseStamped goal_normal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::goal_getter::GoalPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::goal_getter::GoalPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_point);
      stream.next(m.goal_normal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::goal_getter::GoalPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::goal_getter::GoalPose_<ContainerAllocator>& v)
  {
    s << indent << "goal_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_point);
    s << indent << "goal_normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_normal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOAL_GETTER_MESSAGE_GOALPOSE_H
